### ISSUE TITLE
k8s_cluster: Error 400-LimitExceeded, The cluster limit for this tenancy has been exceeded

### ISSUE THREAD

**Issue by Dangimenes** [Rapha-Borges/oke-free#12]
Olá boa tarde.

Estou abrindo essa Issue por que não vi ninguém relatando este problema.

Basicamente segui todos os passos, mas no momento do "terraform apply", recebi o seguinte erro:

module.cluster.oci_containerengine_cluster.k8s_cluster: Creating...
╷
│ Error: 400-LimitExceeded, The cluster limit for this tenancy has been exceeded.
│ Suggestion: Request a service limit increase for this resource Containerengine Cluster
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster
│ API Reference: https://docs.oracle.com/iaas/api/#/en/containerengine/20180222/Cluster/CreateCluster
│ Request Target: POST https://containerengine.us-ashburn-1.oci.oraclecloud.com/20180222/clusters
│ Provider version: 5.24.0, released on 2024-01-10.
│ Service: Containerengine Cluster
│ Operation Name: CreateCluster
│ OPC request ID: 0996e580ca47473ebafa919e706e384c/8DC7642CACC01A8ED5F8923BE728098B/5D3E928F4B5B85C3C3F7067E6E294A3B
│
│
│   with module.cluster.oci_containerengine_cluster.k8s_cluster,
│   on cluster/k8s.tf line 5, in resource "oci_containerengine_cluster" "k8s_cluster":
│    5: resource "oci_containerengine_cluster" "k8s_cluster" {
│
╵
╷
│ Error: 400-InvalidParameter, The maximum limit of 0 for Service gateway per VCN has been exceeded in VCN ocid1.vcn.oc1.iad.amaaaaaaxehdrqqatvmp54jvjuddemvdf5byt2vwe4javbmqyjz4kcb5h6ta.
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message The maximum limit of 0 for Service gateway per VCN has been exceeded in VCN ocid1.vcn.oc1.iad.amaaaaaaxehdrqqatvmp54jvjuddemvdf5byt2vwe4javbmqyjz4kcb5h6ta.
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_service_gateway
│ API Reference: https://docs.oracle.com/iaas/api/#/en/iaas/20160918/ServiceGateway/CreateServiceGateway
│ Request Target: POST https://iaas.us-ashburn-1.oraclecloud.com/20160918/serviceGateways
│ Provider version: 5.23.0, released on . This provider is 15250 Update(s) behind to current.
│ Service: Core Service Gateway
│ Operation Name: CreateServiceGateway
│ OPC request ID: 37eafd91a88c1288604e6ae69346ee41/DCED4039D255C04998FDEF2D4D56406C/17E9103A03C85D5AB538173DB3D01153
│
│
│   with module.vcn.oci_core_service_gateway.service_gateway[0],
│   on .terraform/modules/vcn/vcn_gateways.tf line 127, in resource "oci_core_service_gateway" "service_gateway":
│  127: resource "oci_core_service_gateway" "service_gateway" {
│
╵
╷
│ Error: 400-LimitExceeded, NAT gateway limit per VCN reached
│ Suggestion: Request a service limit increase for this resource Core Nat Gateway
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_nat_gateway
│ API Reference: https://docs.oracle.com/iaas/api/#/en/iaas/20160918/NatGateway/CreateNatGateway
│ Request Target: POST https://iaas.us-ashburn-1.oraclecloud.com/20160918/natGateways
│ Provider version: 5.23.0, released on . This provider is 15250 Update(s) behind to current.
│ Service: Core Nat Gateway
│ Operation Name: CreateNatGateway
│ OPC request ID: ebd225730a96b9012571cca73909321a/806FF145714C57537AD724EA5CEF0C86/6DE947BA02D49CECC52BE7CEFC45C05F
│
│
│   with module.vcn.oci_core_nat_gateway.nat_gateway[0],
│   on .terraform/modules/vcn/vcn_gateways.tf line 177, in resource "oci_core_nat_gateway" "nat_gateway":
│  177: resource "oci_core_nat_gateway" "nat_gateway" {

Obs: alguns recursos foram criados com sucesso, mas quando chegou nesses em específico ocorreu essa falha.

Entendo ser um erro de limite de recursos atingidos, diferente do erro de "out of capacity" que outras pessoas relataram.

Mais alguém obteve esse problema? saberiam como posso resolver?

Detalhe, estou usando uma conta pessoal que eu já tinha na OCI, criada a alguns meses atrás, ele está habilitada sem cartão e no modo free tier, tinha entendido pela documentação que o lab iria funcionar da mesma forma por que todos os recursos criados seriam dentro do free tier e não teriam recursos que consumiriam créditos, mas caso o problema seja relacionado a créditos, peço que me avisem também aí posso tentar correr atrás de criar outra conta

**Comment by Rapha-Borges** [comment]
O erro Error: 400-LimitExceeded, The cluster limit for this tenancy has been exceeded. ocorre porque a sua conta não tem disponibilidade para criar um ou mais recursos necessários no formato atual do laboratório. Uma atualização será realizada nos próximos dias para `Manter Conformidade com o Always Free`; mais informações podem ser encontradas na issue #8.

Até o final do dia de hoje, você pode entrar em contato no [Grupo de Usuários Oracle Cloud](https://t.me/GUOCB) para tentarmos contornar essa situação, criando uma nova conta com bônus oferecidos especialmente para o #MêsDoKubernetes.

> Detalhe, estou usando uma conta pessoal que eu já tinha na OCI, criada a alguns meses atrás, ele está habilitada sem cartão e no modo free tier, tinha entendido pela documentação que o lab iria funcionar da mesma forma por que todos os recursos criados seriam dentro do free tier e não teriam recursos que consumiriam créditos, mas caso o problema seja relacionado a créditos, peço que me avisem também aí posso tentar correr atrás de criar outra conta

**Comment by victooooor** [comment]
> O erro Error: 400-LimitExceeded, The cluster limit for this tenancy has been exceeded. ocorre porque a sua conta não tem disponibilidade para criar um ou mais recursos necessários no formato atual do laboratório. Uma atualização será realizada nos próximos dias para `Manter Conformidade com o Always Free`; mais informações podem ser encontradas na issue #8.
> 
> Até o final do dia de hoje, você pode entrar em contato no [Grupo de Usuários Oracle Cloud](https://t.me/GUOCB) para tentarmos contornar essa situação, criando uma nova conta com bônus oferecidos especialmente para o #MêsDoKubernetes.
> 
> > Detalhe, estou usando uma conta pessoal que eu já tinha na OCI, criada a alguns meses atrás, ele está habilitada sem cartão e no modo free tier, tinha entendido pela documentação que o lab iria funcionar da mesma forma por que todos os recursos criados seriam dentro do free tier e não teriam recursos que consumiriam créditos, mas caso o problema seja relacionado a créditos, peço que me avisem também aí posso tentar correr atrás de criar outra conta

Salve Rafa, acabei de clonar o repo, o terraform ta reclamando:
Error: 400-LimitExceeded, The cluster limit for this tenancy has been exceeded.
│ Suggestion: Request a service limit increase for this resource Containerengine Cluster

Não é problema com seu código, tentei subir manualmente pelo portal e ocorre o mesmo erro, em todas as 3 zonas de disponibilidade!

Out of capacity for shape VM.Standard.A1.Flex in availability domain AD-2. Create the instance in a different availability domain or try again later. If you specified a fault domain, try creating the instance without specifying a fault domain, otherwise try creating the instance in a different availability domain. If that doesn’t work, please try again later.
