### ISSUE TITLE
Erro 404

### ISSUE THREAD

**Issue by danimanfer** [Rapha-Borges/oke-free#2]
Fala Rapha! Estou tomando o erro:

Error: 400-InvalidParameter, Identity DP service returned a 404: 'Compartment id 'ocid1.tenancy.oc1..aaaaaaaah3ncz6tkctx5fp4tgmk6uag6qws33s2y753yohhvkndujqmjav2a' not found'
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message Identity DP service returned a 404: 'Compartment id 'ocid1.tenancy.oc1..aaaaaaaah3ncz6tkctx5fp4tgmk6uag6qws33s2y753yohhvkndujqmjav2a' not found'

**Comment by Rapha-Borges** [comment]
Fala, mano!!

O erro indica que o `Compartment` não foi localizado; talvez tenha ocorrido algum problema na criação dos recursos. Tente executar o `terraform destroy` e, em seguida, `terraform init` com o parâmetro `-upgrade`. Após isso, é só seguir o passo a passo para a criação do cluster.

Se tiver problemas ao rodar o `terraform destroy`, consulte a issue #3, onde expliquei como deletar os recursos manualmente.

**Comment by danimanfer** [comment]
Eu tinha colocado no momento da criação do usuário a região: us-ashburn-1 mas foi criado o usuário na região :  
Brazil East (Sao Paulo). Ta errado ou é assim mesmo. Abaixo a imagem no Tenancy details:
(**OBS:** não foi criado nada na cloud, o erro da logo apos o terraform init, por isso não consegui excluir nada pelo console)
![tenancy](https://github.com/Rapha-Borges/oke-free/assets/45005188/3222bb1c-1991-4b83-b901-a4302118ee6e)

**Comment by Rapha-Borges** [comment]
Infelizmente, a conta foi criada na região 'Brazil East (São Paulo)' em vez de 'US East (Ashburn)'. Talvez você já tenha tido uma conta na região 'Brazil East (São Paulo)' associada a este e-mail anteriormente, o que pode ter causado o erro. Você pode entrar em contato com a equipe da Oracle através do [grupo do Telegram](https://t.me/GUOCB) para tentar resolver essa situação.

**Comment by danimanfer** [comment]
Ja tive conta neste e-mail mesmo la. Vou conversar com o pessoal da Oracle. Obrigado.

**Comment by marcelloale** [comment]
> Ja tive conta neste e-mail mesmo la. Vou conversar com o pessoal da Oracle. Obrigado.

O que eles falaram? estou com o mesmo problema

**Comment by danimanfer** [comment]
> > Ja tive conta neste e-mail mesmo la. Vou conversar com o pessoal da Oracle. Obrigado.
> 
> O que eles falaram? estou com o mesmo problema

Não tem solução para este caso. Teria que fazer um outro cadastro com outro e-mail.
