### ISSUE TITLE
Error: 400-LimitExceeded, The following service limits were exceeded: compartment-count. Request a service limit increase from the service limits page in the console

### ISSUE THREAD

**Issue by MateSousa** [Rapha-Borges/oke-free#20]
Ao realizar o tf apply ocorre esse erro.

│ Error: 400-LimitExceeded, The following service limits were exceeded: compartment-count. Request a service limit increase from the service limits page in the console. 
│ Suggestion: Request a service limit increase for this resource Identity Compartment
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_compartment 
│ API Reference: https://docs.oracle.com/iaas/api/#/en/identity/20160918/Compartment/CreateCompartment 
│ Request Target: POST https://identity.us-ashburn-1.oci.oraclecloud.com/20160918/compartments 
│ Provider version: 5.24.0, released on 2024-01-10.  
│ Service: Identity Compartment 
│ Operation Name: CreateCompartment 
│ OPC request ID: f45d3ee502de8e09448c35244b631559/C619B1F0F5F4B7A644A146EAE183B1F7/DC3555951ADDE07DE8D69E3AD07BCD73 
│ 
│ 
│   with module.compartment.oci_identity_compartment._,
│   on compartment/compartment.tf line 1, in resource "oci_identity_compartment" "_":
│    1: resource "oci_identity_compartment" "_" {

**Comment by dilons** [comment]
Provavelmente tu bateu o limite de compartments da tua região, acredito eu que se vc logar na tua conta oracle e acessar os _compartments_ na região que tu ta usando, e apagar alguns, deve voltar a funcionar.

https://cloud.oracle.com/identity/compartments?region=us-ashburn-1

**Comment by soaresnetoh** [comment]
@Rapha-Borges  @badtuxx ... tenho uma divida? voces sabem se o que foi liberado pela OCI como free desta vez engloba o cluster OKE e o LB usado no codigo Terraform? ou somente o que contempla o free é o mesmo que está no https://www.oracle.com/br/cloud/free/#free-cloud-trial ?

**Comment by Rapha-Borges** [comment]
> @Rapha-Borges @badtuxx ... tenho uma divida? voces sabem se o que foi liberado pela OCI como free desta vez engloba o cluster OKE e o LB usado no codigo Terraform? ou somente o que contempla o free é o mesmo que está no https://www.oracle.com/br/cloud/free/#free-cloud-trial ?

Estamos utilizando o Oracle Container Engine for Kubernetes - Cluster Básico:

![image](https://github.com/Rapha-Borges/oke-free/assets/53947674/a9666ede-4bd3-4e4d-a080-e747ad12cc6a)

E Oracle Cloud Infrastructure Flexible Network Load Balancer:

![image](https://github.com/Rapha-Borges/oke-free/assets/53947674/6fd1f2f2-74dd-4a8b-aa9e-e25c506e44f5)

Os recursos que podem gerar custos são network e storage (em análise).
