### ISSUE TITLE
error 409

### ISSUE THREAD

**Issue by jaksondeoliveiramartins** [Rapha-Borges/oke-free#22]
Error: 409-Conflict, Kubernetes version does not match Kubernetes version of OKE worker node image (v1.26.7)
│ Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Containerengine Node Pool
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_node_pool
│ API Reference: https://docs.oracle.com/iaas/api/#/en/containerengine/20180222/NodePool/CreateNodePool
│ Request Target: POST https://containerengine.us-ashburn-1.oci.oraclecloud.com/20180222/nodePools
│ Provider version: 5.25.0, released on . This provider is 15250 Update(s) behind to current.
│ Service: Containerengine Node Pool
│ Operation Name: CreateNodePool
│ OPC request ID: d6b5f9e51d4def473b9210efc46ee8d7/44852AB8B6E1134F8B6D9822B7E3E7C1/F13CAA5C066F9783CD4F962FEC2D5920
│
│
│   with module.cluster.oci_containerengine_node_pool.k8s_node_pool,
│   on cluster\k8s.tf line 29, in resource "oci_containerengine_node_pool" "k8s_node_pool":
│   29: resource "oci_containerengine_node_pool" "k8s_node_pool" {

**Comment by Rapha-Borges** [comment]
Erro ao inserir os valores das variáveis no arquivo `variables.tf`.

A imagem utilizada para o(s) worker(s) não é compatível com a versão do Kubernetes configurada para o Control Plane.
