### ISSUE TITLE
Migrar o projeto para OpenTofu

### ISSUE THREAD

**Issue by Rapha-Borges** [Rapha-Borges/oke-free#27]
- [X] Inserir um guia passo a passo para a instalação do OpenTofu.
- [X] Substituir os comandos `terraform` por `tofu`.
- [x] Validar procedimento de instalação
- [x] Revisar README

**Comment by nataliagranato** [comment]
### Validação do procedimento de instalação

- Instrução de criação de API Key e de variavies de ambiente corretos.
- Inicialização do tofu init funcionando corretamente.
- Plano de criação de infraestrutura com o tofu plan correto.
- Criação de cluster OKE funcionando corretamente.
- Utilização do tofu output public_ip para obter o IP do load balancer funcionando corretamente.

![2024-01-31_23-47](https://github.com/Rapha-Borges/oke-free/assets/91998391/af45700e-6e48-4a5e-bb24-1c205109e52a)

**Comment by Rapha-Borges** [comment]
Muito obrigado pela colaboração na validação não apenas da migração para o OpenTofu, mas também na validação de todos os passos no processo de criação do cluster.

**Comment by nataliagranato** [comment]
De nada. Apenas pra não gerar confusão, é necessário "migrar" o main.sh para tofu.

**Comment by Rapha-Borges** [comment]
O script para criação do cluster precisa ser completamente revisado e atualizado, pois não acompanhou as atualizações do projeto. 

@arthurhenrique posso abrir uma issue solicitando ajuda, ou você gostaria de fazer?

**Comment by arthurhenrique** [comment]
opa @Rapha-Borges se o tofu é compativel com terraform, o trampo seria renomear e testar a criação de um cluster novo?

**Comment by Rapha-Borges** [comment]
> opa @Rapha-Borges se o tofu é compativel com terraform, o trampo seria renomear e testar a criação de um cluster novo?

Acredito que basicamente seria isso. O principal é validar a criação, já que o OpenTofu é totalmente compatível com Terraform.

Analisando o script, não vejo necessidade de migrar para autenticação por API KEY. Acredito que isso tiraria totalmente a praticidade do script, já que seria necessário realizar boa parte do processo de forma "manual". Alguma sugestão?

**Comment by Rapha-Borges** [comment]
- Seria legal também alterar a parte da chave SSH para ficar conforme o readme `./ssh/id_rsa`.

```
# ssh_handler
# generating and export var
ssh_handler(){
    if ! [[ -f ./ssh/id_rsa.pub ]]; then
        echo "generating rsa key"
        mkdir -p ./ssh
        ssh-keygen -t rsa -b 4096 -f ./ssh/id_rsa
    fi
}
```

```
export TF_VAR_ssh_public_key=$(cat ./ssh/id_rsa.pub)
```

- Fiz alguns testes com a autenticação via API KEY e o script funciona corretamente na primeira execução. Somente falha se for necessário o `t_retry_apply` pois ele chama a função `refresh_token`.  O que acha de adicionarmos uma instrução conforme exemplo abaixo:

```
# t_retry_apply
# retry apply tofu until succeded
t_retry_apply(){
    retry_sleep=10;

    while [[ true ]]; do
        t_plan
        t_apply

        echo "retry tofu apply... retrying in " $retry_sleep " seconds"
        sleep $retry_sleep
        refresh_token # Comment this line if you are using a different authentication method (e.g. API Key).
    done
```

@arthurhenrique
