### ISSUE TITLE
ao dar tofu apply pede variaveis

### ISSUE THREAD

**Issue by jilherme** [Rapha-Borges/oke-free#36]
Eu tinha tentado fazer o passo-a-passo na semana que lançou o repo, utilizando o windows, mas nao obtive sucesso. Estava tentando fazer pelo PopOS porém na parte de dar o `tofu apply` ele me pede as variaveis.

![image](https://github.com/Rapha-Borges/oke-free/assets/74925460/cf2810ea-2f5c-430c-b09a-bb92da84d3eb)

eu criei o env.sh e rodei. Testei com o comando `printenv` e estavam aparecendo, to meio que sem ter pra onde correr já 

P.S.: só consegui dar init e tentar dar apply como sudo, senao dava mensagem sobre permissoes do terraform.

**Comment by nataliagranato** [comment]
Isso aconteceu comigo quando não realizei o passo de autenticando na OCI completamente, se você inicializar o projeto com tofu init e tofu apply ele vai te pedir pra inserir essas informações.

**Comment by Rapha-Borges** [comment]
Se você exportar as variáveis como usuário "normal" e, em seguida, executar o Tofu (ou Terraform) como `sudo`, ele não encontrará os valores. Este é o comportamento normal e esperado.

Aconselho que volte para o passo de instalação do OpenTofu e tente identificar qualquer erro relacionado às permissões, pois por padrão, não é necessário usar `sudo` para os comandos do Tofu.

**Comment by jilherme** [comment]
sexta de noite irei dar uma olhada de novo nisso! Obrigado pela atenção, pessoal.

**Comment by jilherme** [comment]
Consegui! Depois de mexer no ~/.oci/config, um chmod 777 no `oke-free`, tentar rodar e continuar dando erro e depois funcionou kkkkk.

![image](https://github.com/Rapha-Borges/oke-free/assets/74925460/8338c6ad-a8e6-4140-863b-4f4eaa0a4e19)
