### ISSUE TITLE
Erro status critical no Load Balancer

### ISSUE THREAD

**Issue by JoaoXavier-AnalystM** [Rapha-Borges/oke-free#38]
Ao realizar o processo de **apply** todo processo se constrói como o esperado, porem observei os seguinte erro abaixo:
![Erro loadbalancer](https://github.com/Rapha-Borges/oke-free/assets/67073271/70bc5134-40ae-4a05-a82f-e5e2221f88e4)

Que creio que seja o motivo por minha stack(prometheus/grafana) não estejam ficando disponíveis.

Se puder da uma força @Rapha-Borges

**Comment by JoaoXavier-AnalystM** [comment]
ajustado

**Comment by Rapha-Borges** [comment]
Agradeço se puder colaborar informando qual foi o erro e como foi resolvido, pois isso pode auxiliar outras pessoas que possam ter o mesmo problema. Ou até mesmo me ajudar a corrigir/atualizar alguma parte do código.
