### ISSUE TITLE
Adicionar Ingress como exemplo de uso

### ISSUE THREAD

**Issue by Rapha-Borges** [Rapha-Borges/oke-free#40]
Atualmente temos duas opções de implementação para o Ingress Controller. Será necessário revisar ambas e decidir qual delas será adotada como padrão no repositório:

- [ ] ~~PR #39~~
- [x] PR #43 

Após a escolha da implementação, alguns passos devem ser validados antes da conclusão do merge:

- [x] Validar arquivos YAML
- [x] Executar testes utilizando o cluster criado nesse repositório
- [x] Criar/revisar documentação de como implementar e configurar o Ingress

**Comment by soaresnetoh** [comment]
não vi esta issue ... mas mandeu um PR.. vê se ajuda? #44
