### ISSUE TITLE
Estou tentando esse problema.

### ISSUE THREAD

**Issue by thiagousa** [Rapha-Borges/oke-free#46]
module.cluster.oci_containerengine_node_pool.k8s_node_pool: Still creating... [1m0s elapsed]
module.cluster.oci_containerengine_node_pool.k8s_node_pool: Still creating... [1m10s elapsed]
╷
│ Error: Work Request error 
│ Provider version: 5.29.0, released on 2024-02-15.  
│ Service: Containerengine Node Pool
│ Error Message: work request did not succeed, workId: ocid1.clustersworkrequest.oc1.iad.aaaaaaaa6kwpbat5wl42zlqx3rhjyldc5b5rlwo2klbfkshlswivbfuqwumq, entity: nodepool, action: CREATED. Message: 2 node(s) launch failure. Reason for failure on one of the nodes : Error returned by Unknown operation operation in Unknown service service.(500, InternalError, false) Out of host capacity. (opc-request-id: 3CB6F935FDD14DDF84A46620FAE6E3B0/FDEF32254979E4BF90CFC5E8E58A3EFA/8FF13BA29C359FFA65A33D0D99D4C5A5)
│ Timestamp: 2024-02-21T13:51:55.828Z
│ Client version: Oracle-JavaSDK/2.66.1
│ Request Endpoint: Unknown request endpoint
│ Troubleshooting Tips: See https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm#apierrors_500__500_internalerror for more information about resolving this errorre information about resolving this error
│ Also see Unknown API reference link for details on this operation's requirements.                                                        s.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconfig.htm.       
│ To get more info on the failing request, you can enable debug level logs as mentioned in `Using SLF4J for Logging section` in https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconfig.htm.
│ If you are unable to resolve this Unknown service issue, please contact Oracle support and provide them this full error message.
│ Resource OCID: ocid1.nodepool.oc1.iad.aaaaaaaawdbfvnpttx5vzdd7xoexfxi3td3bzcqp7s6pphjbnnl7ymkzu5aa
│ Suggestion: Please retry or contact support for help with service: Containerengine Node Pool
│
│
│   with module.cluster.oci_containerengine_node_pool.k8s_node_pool,
│   on cluster/k8s.tf line 29, in resource "oci_containerengine_node_pool" "k8s_node_pool":
│   29: resource "oci_containerengine_node_pool" "k8s_node_pool" {

**Comment by Rapha-Borges** [comment]
## 500 InternalError Out of host capacity

O motivo e a solução desse erro está presente no README.md

https://github.com/rapha-Borges/oke-free?tab=readme-ov-file#pontos-importantes-antes-de-come%C3%A7ar

https://github.com/rapha-Borges/oke-free?tab=readme-ov-file#se-voc%C3%AA-tentar-criar-um-cluster-com-uma-conta-gratuita-e-receber-o-erro-abaixo
