### ISSUE TITLE
Work Request error

### ISSUE THREAD

**Issue by henri-31** [Rapha-Borges/oke-free#6]
Estou recebendo o seguinte erro no momento de dar o apply no terraform:

Error: Work Request error 
│ Provider version: 5.24.0, released on 2024-01-10.  
│ Service: Containerengine Node Pool 
│ Error Message: work request did not succeed, workId: ocid1.clustersworkrequest.oc1.iad.aaaaaaaa3zzu6fkjsjhdp2h5pgmxepgu3fxjzokgqvwl3f7krwhxkf763ggq, entity: nodepool, action: CREATED. Message: 1 nodes(s) register timeout. First, confirm that network prerequisites have been met. If network prerequisites have been met, troubleshoot the problem by running the Node Doctor script on the node(s) experiencing the issue, using either SSH or the Run Command feature. If you cannot resolve the issue using the t

**Comment by paulovieirajr** [comment]
Mesma coisa aqui... 😥

**Comment by Rapha-Borges** [comment]
Em tratamento #5
